name: dodge_the_spikes
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.3.0
  flame_audio: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/board_tile.png
    - assets/images/bee.png
    - assets/images/bee_2.png
    - assets/images/flower.png
    - assets/images/add_one.png
    - assets/images/subtract_one.png
    - assets/images/add_two.png
    - assets/images/subtract_two.png
    - assets/images/enemy.png
    - assets/images/explosion_1.png
    - assets/images/explosion_2.png
    - assets/images/explosion_3.png
    - assets/images/explosion_4.png
    - assets/images/explosion_5.png
    - assets/images/explosion_6.png
    - assets/images/explosion_7.png
    - assets/images/explosion_8.png
    - assets/images/explosion_9.png
    - assets/images/explosion_10.png
    - assets/images/arrow.png
    - assets/audio/background_music.wav
    - assets/audio/c.wav
    - assets/audio/e.wav
    - assets/audio/g.wav
    - assets/audio/a.wav
    - assets/audio/game_over.wav
    - assets/audio/win.wav

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
    - family: Silkscreen-Bold
      fonts:
        - asset: fonts/Silkscreen-Bold.ttf
    - family: Silkscreen-Regular
      fonts:
        - asset: fonts/Silkscreen-Regular.ttf

